---
specfile_path: karel.spec
upstream_package_name: karel-the-robot
downstream_package_name: libkarel

srpm_build_deps: []

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-all
  - opensuse-tumbleweed
  - opensuse-15.3

- job: copr_build
  trigger: commit
  branch: main
  owner: mfocko
  project: karel
  targets:
  - fedora-all
  - opensuse-tumbleweed
  - opensuse-15.3
