# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mirek/Projects/tuke/programovanie/libkarel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mirek/Projects/tuke/programovanie/libkarel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mirek/Projects/tuke/programovanie/libkarel/CMakeFiles /home/mirek/Projects/tuke/programovanie/libkarel/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mirek/Projects/tuke/programovanie/libkarel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named karel

# Build rule for target.
karel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 karel
.PHONY : karel

# fast build rule for target.
karel/fast:
	$(MAKE) -f CMakeFiles/karel.dir/build.make CMakeFiles/karel.dir/build
.PHONY : karel/fast

src/internals.o: src/internals.c.o

.PHONY : src/internals.o

# target to build an object file
src/internals.c.o:
	$(MAKE) -f CMakeFiles/karel.dir/build.make CMakeFiles/karel.dir/src/internals.c.o
.PHONY : src/internals.c.o

src/internals.i: src/internals.c.i

.PHONY : src/internals.i

# target to preprocess a source file
src/internals.c.i:
	$(MAKE) -f CMakeFiles/karel.dir/build.make CMakeFiles/karel.dir/src/internals.c.i
.PHONY : src/internals.c.i

src/internals.s: src/internals.c.s

.PHONY : src/internals.s

# target to generate assembly for a file
src/internals.c.s:
	$(MAKE) -f CMakeFiles/karel.dir/build.make CMakeFiles/karel.dir/src/internals.c.s
.PHONY : src/internals.c.s

src/karel.o: src/karel.c.o

.PHONY : src/karel.o

# target to build an object file
src/karel.c.o:
	$(MAKE) -f CMakeFiles/karel.dir/build.make CMakeFiles/karel.dir/src/karel.c.o
.PHONY : src/karel.c.o

src/karel.i: src/karel.c.i

.PHONY : src/karel.i

# target to preprocess a source file
src/karel.c.i:
	$(MAKE) -f CMakeFiles/karel.dir/build.make CMakeFiles/karel.dir/src/karel.c.i
.PHONY : src/karel.c.i

src/karel.s: src/karel.c.s

.PHONY : src/karel.s

# target to generate assembly for a file
src/karel.c.s:
	$(MAKE) -f CMakeFiles/karel.dir/build.make CMakeFiles/karel.dir/src/karel.c.s
.PHONY : src/karel.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... karel"
	@echo "... edit_cache"
	@echo "... src/internals.o"
	@echo "... src/internals.i"
	@echo "... src/internals.s"
	@echo "... src/karel.o"
	@echo "... src/karel.i"
	@echo "... src/karel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

